version: 2
updates:
  - package-ecosystem: "python"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main" # Specify the branch to update
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    automerge: true # Enable automerging if desired
    labels:
      - "dependencies"
