version: '3.8'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://mendicant:password@postgres:5432/mendicant_dev
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: python app.py

  webhook:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://mendicant:password@postgres:5432/mendicant_dev
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: python scripts/webhook_handler.py

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mendicant_dev
      - POSTGRES_USER=mendicant
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://mendicant:password@postgres:5432/mendicant_dev
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: celery -A src.celery_app worker --loglevel=info

volumes:
  postgres_data: