name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub gradio

      - name: Hugging Push
        uses: backendcloud/hugging-push@v0.2.3
        with:
          huggingface_repo: 'Canstralian/PyLintPro'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
          private: false
          space_sdk: 'gradio'

      - name: Verify Deployment
        run: echo "Deployment completed. Verifying..."

      - name: Notify Result
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Deployment to Hugging Face successful!"
          else
            echo "Deployment to Hugging Face failed. Please check the logs for more details."
          fi
