name: Enhanced CI Pipeline

on: [push, pull_request]

# Cancel any in-progress runs on the same branch or PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint with Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python & Cache Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Flake8
        run: |
          pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        uses: py-actions/flake8@v2
        with:
          args: . --count --select=E9,F63,F7,F82 --show-source --statistics

  test-and-coverage:
    name: Test Matrix & Coverage
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python & Cache Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Test Dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-cov codecov

      - name: Run Pytest with Coverage
        run: pytest --maxfail=1 --disable-warnings --cov=./ --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_when_error: true

  notify:
    name: Slack Notification
    needs: [lint, test-and-coverage]
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack of Workflow Result
        if: always()
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: |
            *CI Pipeline* completed with status: `${{ job.status }}`
          channel: ci-notifications